repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: trufflehog
        entry: trufflehog
        args: ["git", "file://.", "--since-commit", "HEAD", "--no-verification", "--fail"]
        pass_filenames: false
        language: system
        description: "Run trufflehog with --no-verification on the latest commit"

