name: releases

on:
  push:
    tags:
      - '*'

jobs:
  build-publish-attest:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      attestations: write
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build the Project
        run: |
          poetry build
          ls dist/

      - name: Generate SBOM using CycloneDX
        run: |
          poetry run cyclonedx-py poetry > cyclonedx-sbom.json

      - name: Generate SBOM Attestation
        uses: actions/attest-sbom@v2
        with:
          subject-path: 'dist/*.whl'
          sbom-path: 'cyclonedx-sbom.json'

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist/

      - name: Upload SBOM and Attestation
        uses: actions/upload-artifact@v3
        with:
          name: sbom-and-attestation
          path: |
            cyclonedx-sbom.json
            sbom-attestation.bundle

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*  
            cyclonedx-sbom.json  
            sbom-attestation.bundle  
          body: |
            This release includes:
            - Build artifacts 
            - SBOM 
            - SBOM Attestation 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
