name: Python Linting and Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run Ruff Linter
        run: poetry run ruff check .

      - name: Run Black
        run: poetry run black . --check

      - name: Run Pylint
        run: poetry run pylint .
      
      - name: Run Bandit 
        run: poetry run bandit -r .

      - name: Run TruffleHog
        run: |
          pip install trufflehog
          trufflehog filesystem --repo-path . || exit 1

